### ISSUE TITLE
First scan UX is messy on Android

### ISSUE THREAD

**Issue by ceddup** [getcanoe/canoe#145]
Many qwirks here, first user is asked for password, then android confirmation doubles with Canoe confirmation

**Comment by gokr** [comment]
I don't understand.

**Comment by ceddup** [comment]
Well it's just as I described it. From a scratch install, you get through login then double confirmation. I'll test it again.

**Comment by rtaibah** [comment]
To clarify what @ceddup is saying: When a user first installs an app, goes through the onboarding, and now using the app. The first time a user taps on the 'scan' tab, they are asked to enter the password.

**Comment by gokr** [comment]
Ok, I will look at it eventually

Den tis 27 feb 2018 11:53Rami Taibah <notifications@github.com> skrev:

**Comment by ceddup** [comment]
Yes and the app asks you if you want to allow it to use the camera, then Android (the system) asks you again. This was already there before the password was added.

**Comment by rtaibah** [comment]
This bug is tied with the 'timeout' functionality. What is happening right now is the app is locking because Android is asking for permission to access the camera which is theoretically moving the focus away from Canoe. Then the user is dumped back to the app, they are asked for a password.

It's a cop out, but one can just implement 'timeout' and set the default timeout to be 10 seconds. The problem will go away, unless a user waits for 10 seconds before responding to the permissions modal.

**Comment by gokr** [comment]
New default settings for locks should solve this, we need to confirm.

**Comment by gokr** [comment]
Verified it works.
