### ISSUE TITLE
When choosing "max" send button disappears and Fiat conversion breaks

### ISSUE THREAD

**Issue by stefonarch** [getcanoe/canoe#259]
Send button never appears when hitting max button.
Conversion is broken after that too, and  input can be anything. Only way to exit redo send
![schermata-19-14-15-15](https://user-images.githubusercontent.com/10681413/38990860-1edf06ec-43dc-11e8-943c-29857423358b.png)

**Comment by Stormtv** [comment]
I'm having issues replicating the problem here, when I hit send max it adds the total to the amount string and the blue send arrow appears. Conversion was a different bug that was due to the test.getcanoe.io server not sending rate amounts. Any additional information would be extremely helpful so we can get 0.3.6 out today

**Comment by Stormtv** [comment]
Finally fixed this thanks to @stefonarch for helping me narrow down that this was a localization bug
https://github.com/getcanoe/canoe/commit/a6be01e4e387fedfa3c2ce17830063128c635d60
