### ISSUE TITLE
Display pending funds as an hourglass 

### ISSUE THREAD

**Issue by rtaibah** [getcanoe/canoe#64]
Let's have a pending hourglass/clock somewhere instead of the '0.000 XRB <--- .0003'

For more information a user should go to the transaction page by tapping on the wallet.

![screenshot_20180110-193700](https://user-images.githubusercontent.com/707668/34784355-11b69902-f63f-11e7-9332-8d3b964e9430.png)

**Comment by gokr** [comment]
The clock is now removed, people had a hard time understanding what it was including myself. It had to do with the fact that Copay operates with remote wallets - and thus balances are cached and have a "time since last read" etc. But Canoe doesn't do that, we have a balance and that's it. I ripped out the cache blabla. How to render pending is still an open question, it uses still the arrow.

**Comment by ceddup** [comment]
Can we close?
